version: '3'

services:
  mon_postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskmanager
      - DB_TYPE=${DB_TYPE}
    ports:
      - "5432:5432"
    volumes:
      - /home/lolo/Projects/TaskManager/data/postgres:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
